### ISSUE TITLE
Commands not working on MS Windows

### ISSUE THREAD

**Issue by ddgenome** [atomist/cli#2]
Commands are not working on MS Windows since the switch from `child_process.exec` to `child_process.spawn`.

`exec` spawns a shell which properly deals with both `.exe`, `.bat`, and `.cmd` files on MS Windows. `spawn` properly handles `.exe` but not `.bat` and `.cmd`. See https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows for the current status and nodejs/node-v0.x-archive#2318 for more context.

Reference: https://nodejs.org/api/child_process.html

**Comment by ddgenome** [comment]
The best way to preserve proper argument parsing and allow for `.bat` and `.cmd` support is probably to specify `{ shell: true }`.

It might also be better to use `child_process.fork` when running node commands, but I feel like there was a reason I didn't do that already.

**Comment by ddgenome** [comment]
The above commit does set `{ shell: true }` for spawn.

Rather than use `child_process.fork`, which opens an IPC channel between processes we do not need, I improved the use of spawning node by using `process.execPath` rather than smarts to determine the name of the node executable.

**Comment by ddgenome** [comment]
`process.execPath` caused issues on MS Windows because the full path had directories with spaces in it. That should not cause a problem, but it is mentioned in the docs. Switching to `process.argv0`.

**Comment by ddgenome** [comment]
@lievendoclo are things working on MS Windows now?

**Comment by lievendoclo** [comment]
No, they don't. `atomist new sdm` fails with an error. `Cannot read property 'startsWith' of undefined`

**Comment by ddgenome** [comment]
@lievendoclo I've updated the CLI to use cross-spawn, at least for its core commands. Can you see if config, start, and kube work in the latest master on MS Windows?

The git and gql-gen commands have moved to automation-client. Update your project to `@atomist/automation-client@0.20.1`. Then update the package.json scripts to:

```javascript
    "git:info": "node node_modules/@atomist/automation-client/start.git-info.js",
    "gql:gen": "node node_modules/@atomist/automation-client/start.gql-gen.js",
```

The start.git-info.ts does not use child_process at all, so it should be OK. The start.gql-gen.ts was changed to use child_process.fork(). Does it work on MS Windows?

**Comment by lievendoclo** [comment]
Ok, most commands work now
However, if people on windows use the bash shell (which they will have when they installed Git) instead of the windows command line, we're back to square one as we cannot use the .cmd scripts when we're in a Bash shell

**Comment by ddgenome** [comment]
Is there a way on MS Windows to know whether node was invoked by cmd.exe or Bash?

**Comment by ddgenome** [comment]
I spun up an MS Windows 10 VM with the Linux/Bash subsystem installed. The Windows version of Node.js does not appear to work very well under the Linux subsystem. The solution is to install Node.js within the Linux subsystem. Once you do this, everything seems to work as expected on a POSIX system. Even `process.platform` is `linux`.

**Comment by ddgenome** [comment]
The native CLI commands should all work now on MS Windows. Issues with the commands brought in by sdm-local will be dealt with in that repository.

**Comment by ddgenome** [comment]
I think everything in CLI is working now so I'm closing this. Any remaining issues are likely in sdm-local.
