### ISSUE TITLE
Give indication of input when pasting APIKey

### ISSUE THREAD

**Issue by jessitron** [atomist/cli#23]
That hidden input was a problem, because we could not tell whether we had pasted it in, and the result we got was like ten copies of the APIKey concatenated. Either don't hide it or make it show dots or somethign

**Comment by ddgenome** [comment]
Unfortunately, using inquirer there is no masking option. We'd either have to keep it how it is or show it.

Can you provide more information on your experience? You pasted but weren't sure you pasted?

**Comment by jessitron** [comment]
In this terminal (on Windows! and it's working), "paste" is right-click. It's hard to know whether it really pasted anything. In the end we had to open the client config file to find out whether the API key was in there, and found it in there many times. So, hiding it was not helpful

**Comment by ddgenome** [comment]
Sounds like your vote would be just to not mask it at all?

**Comment by ddgenome** [comment]
I found a way to indicate input but still have it masked. See #25.
