### ISSUE TITLE
Make a more clear prompt than '? (mapped parameter) target-owner'

### ISSUE THREAD

**Issue by jessitron** [atomist/cli#47]

**Comment by ddgenome** [comment]
Wouldn't this be in sdm-local?

**Comment by cdupuis** [comment]
@jessitron you indicated that you did this already. Where?

**Comment by cdupuis** [comment]
Looks like this was committed https://github.com/atomist/sdm-local/commit/e03434a7cc9b79ded69764781c158ee4d0a61bcc which was after the 1.0.5 release. This will go out with the next release.

@jessitron are you happy to close this then?

**Comment by jessitron** [comment]
oh great, yeah I was wondering about where that was. thank you
